theme: jekyll-theme-minimal
logo: staticfiles/img/logo-icon-64x64.png
title: The Chronicles of Dan
description: Hi, I'm Dan, a creator, programmer, coffee lover and baker. Here are the chronicles of my personal projects!
